### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by yangton** [ThePBone/RootlessJamesDSP#212]
The application crashes on the latest Android beta version on the Pixel 6 device version of Android:

**Crash 1 log**:
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

SystemUptimeMs: 1327175
Process: me.timschneeberger.rootlessjamesdsp
PID: 30366
UID: 10588
Frozen: false
Flags: 0x20c8be44
Package: me.timschneeberger.rootlessjamesdsp v45 (1.6.8)
Foreground: Yes
Process-Runtime: 4310
Build: google/oriole_beta/oriole:14/AP21.240216.010/11529813:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at me.timschneeberger.hiddenapi_impl.ShizukuSystemServerApi.PermissionManager_grantRuntimePermission(ShizukuSystemServerApi.java:49)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.ensureDumpPermission(OnboardingFragment.kt:487)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.canAccessNextPage(OnboardingFragment.kt:463)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage(OnboardingFragment.kt:426)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage$default(OnboardingFragment.kt:419)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:250)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:222)
	at me.timschneeberger.rootlessjamesdsp.view.Card._init_$lambda$1(Card.kt:133)
	at me.timschneeberger.rootlessjamesdsp.view.Card.$r8$lambda$O4AgqJI0zQIWi33ObcCsXniNjEY(Unknown Source:0)
	at me.timschneeberger.rootlessjamesdsp.view.Card$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7897)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7874)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30843)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8583)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Crash 2 log**:
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

SystemUptimeMs: 1321483
Process: me.timschneeberger.rootlessjamesdsp
PID: 30284
UID: 10588
Frozen: false
Flags: 0x20e8be44
Package: me.timschneeberger.rootlessjamesdsp v45 (1.6.8)
Foreground: Yes
Process-Runtime: 5221
Build: google/oriole_beta/oriole:14/AP21.240216.010/11529813:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 3

java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at me.timschneeberger.hiddenapi_impl.ShizukuSystemServerApi.PermissionManager_grantRuntimePermission(ShizukuSystemServerApi.java:49)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.ensureDumpPermission(OnboardingFragment.kt:487)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.canAccessNextPage(OnboardingFragment.kt:463)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage(OnboardingFragment.kt:426)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage$default(OnboardingFragment.kt:419)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$OnRequestPermissionResult.onRequestPermissionResult(OnboardingFragment.kt:328)
	at rikka.shizuku.Shizuku.dispatchRequestPermissionResultListener(Shizuku.java:296)
	at rikka.shizuku.Shizuku.lambda$scheduleRequestPermissionResultListener$1(Shizuku.java:290)
	at rikka.shizuku.Shizuku$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8583)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by yangton** [comment]
error indicates that your application is attempting to call a method that doesn't exist within a particular class during runtime.
Specifics from the Logs: The method in question is grantRuntimePermission within the android.permission.IPermissionManager interface. The method cannot be found, strongly suggesting an incompatibility with Android 14 Beta.
So wait for the update or maybe there is someone willing to solve this problem together, I greet
