### ISSUE TITLE
App stops/crashes while granting access to Shizuku on Pixel 6a

I'm using Pixel 6a with latest Android 14 release(AP1A.240405.002)

### ISSUE THREAD

**Issue by piedpipr** [ThePBone/RootlessJamesDSP#215]
The app keeps crashing while granting access to Shizuku on the screen as shown below

![Screenshot_20240405-170028.png](https://github.com/ThePBone/RootlessJamesDSP/assets/43669876/b088515d-fd4b-4fbd-82a3-5cf52a8e74a4)

Meaning in Shizuku it already has been allowed. However the same option shows which is not granted and ask for it. Upon tapping grant access or next the app crashes.

**Comment by Entity1011** [comment]
Same issue here, I'd also like to bump this

**Comment by wizzdom** [comment]
Same here on Pixel 8 Pro A14 Build AP1A.240405.002

```
FATAL EXCEPTION: main
Process: me.timschneeberger.rootlessjamesdsp, PID: 23755
java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at me.timschneeberger.hiddenapi_impl.ShizukuSystemServerApi.PermissionManager_grantRuntimePermission(ShizukuSystemServerApi.java:49)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.ensureDumpPermission(OnboardingFragment.kt:487)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.canAccessNextPage(OnboardingFragment.kt:463)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage(OnboardingFragment.kt:426)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage$default(OnboardingFragment.kt:419)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:250)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:222)
	at me.timschneeberger.rootlessjamesdsp.view.Card._init_$lambda$1(Card.kt:133)
	at me.timschneeberger.rootlessjamesdsp.view.Card.$r8$lambda$O4AgqJI0zQIWi33ObcCsXniNjEY(Unknown Source:0)
	at me.timschneeberger.rootlessjamesdsp.view.Card$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7729)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by harshil21** [comment]
Yeah I had the same issue. They actually fixed it in https://github.com/timschneeb/RootlessJamesDSP/commit/a2205b373a874dad7ddbfa0f59eb3dfee3709d93 but they didn't make another release. You can grab the latest build from https://github.com/timschneeb/RootlessJamesDSP/actions/runs/8420122395

**Comment by MatyasDoktor** [comment]
There is a workaround. You can enable the app via ADB. You can do this on a PC or on your phone.

For your phone 1. Install aShell for Shizuku on fdroid; if you search "shizuku" it is the only app that pops up. 2. Uninstall and reinstall JamesDSP. 3. Select the use a PC option when setting up instead of Shizuku. 4. Copy the commands from the setup in James DSP into aShell for Shizuku one at a time. 5. Hit next and the latest build should be fully working and circumvent the crash.

**Comment by MKBontwikkeling** [comment]
> There is a workaround. Y ou can enable the app via ADB. You can do this on a PC or on your phone.
> 
> For your phone 1. Install aShell for Shizuku on fdroid; if you search "shizuku" it is the only app that pops up. 2. Uninstall and reinstall JamesDSP. 3. Select the use a PC option when setting up instead of Shizuku. 4. Copy the commands from the setup in JamesDSP into aShell for Shizuku one at a time and execute the command with the arrow on the right after pasting each command. 5. Hit next in JamesDSP and the latest build should be fully working and circumvent the crash.

I can't seem to make it word using aShell, because there isn't a permission added to the ADB commands. But I'm just a noob.

It would be great if someone could make another release from a2205b3. Those APK links all say expired.

Would this be possible? I love the project!

**Comment by harshil21** [comment]
> It would be great if someone could make another release from [a2205b3](https://github.com/timschneeb/RootlessJamesDSP/commit/a2205b373a874dad7ddbfa0f59eb3dfee3709d93). Those APK links all say expired.

i'm too lazy to build it, but here's the build from the [latest commit](https://github.com/timschneeb/RootlessJamesDSP/commit/cb86dcdf0889d275a600412a356e5deef1ca7363) - https://github.com/timschneeb/RootlessJamesDSP/actions/runs/9698898916

Also I moved to an app called "SoundID" which customizes the audio based on your preference / hearing. Not as customizable as this, but that app doesn't require Shizuku

**Comment by geomusicmaker** [comment]
> Yeah I had the same issue. They actually fixed it in https://github.com/timschneeb/RootlessJamesDSP/commit/a2205b373a874dad7ddbfa0f59eb3dfee3709d93 but they didn't make another release. You can grab the latest build from https://github.com/timschneeb/RootlessJamesDSP/actions/runs/8420122395

Hi, I'm a noob, can you explain how I can get this unreleased build?

**Comment by harshil21** [comment]
> > Yeah I had the same issue. They actually fixed it in [a2205b3](https://github.com/timschneeb/RootlessJamesDSP/commit/a2205b373a874dad7ddbfa0f59eb3dfee3709d93) but they didn't make another release. You can grab the latest build from https://github.com/timschneeb/RootlessJamesDSP/actions/runs/8420122395
> 
> Hi, I'm a noob, can you explain how I can get this unreleased build?

Well on the repo home page, click on the green checkmark on the latest commit > Click on "Details" for the rootless build > then click on "Summary" on the left panel > Scroll down and download the rootless apk (most android phones are on arm64-v8a)

**Comment by geomusicmaker** [comment]
> > > Yeah I had the same issue. They actually fixed it in [a2205b3](https://github.com/timschneeb/RootlessJamesDSP/commit/a2205b373a874dad7ddbfa0f59eb3dfee3709d93) but they didn't make another release. You can grab the latest build from https://github.com/timschneeb/RootlessJamesDSP/actions/runs/8420122395
> > 
> > 
> > Hi, I'm a noob, can you explain how I can get this unreleased build?
> 
> Well on the repo home page, click on the green checkmark on the latest commit > Click on "Details" for the rootless build > then click on "Summary" on the left panel > Scroll down and download the rootless apk (most android phones are on arm64-v8a)

Thanks for your explanation. I found the preview apk and installed it. Unfortunately, the issue persists for me. When I try to grant Shizuku permissions it comes up with the OS message to grant it and then crashes. The Shizuku app and the OS both seem to think it has the permissions but the app itself can't get past that point.

I'm on Pixel OS 14 on a Redmi Note 10 Pro if that helps any.

**Comment by shak38** [comment]
Hi, same problem here, on android 14 trying to grant Shizuku permissions crashes the app with the new build...
